import type {ChordTemplate} from './interfaces'

export const PITCH_CLASS_NAMES_SHARP = [
    'C',
    'C#',
    'D',
    'D#',
    'E',
    'F',
    'F#',
    'G',
    'G#',
    'A',
    'A#',
    'B',
]

export const CHORD_TEMPLATES: ChordTemplate[] = [
    {
        type: 'major',
        intervals: [0, 4, 7],
        requiredIntervals: [0, 4, 7],
        signatureIntervals: [],
        symbolSuffix: '',
        priority: 10,
        category: 'triad',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'minor',
        intervals: [0, 3, 7],
        requiredIntervals: [0, 3, 7],
        signatureIntervals: [],
        symbolSuffix: 'm',
        priority: 10,
        category: 'triad',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'power',
        intervals: [0, 7],
        requiredIntervals: [0, 7],
        optionalIntervals: [],
        omittableIntervals: [],
        signatureIntervals: [],
        symbolSuffix: '5',
        priority: 11,
        category: 'triad',
        qualityDependsOnThird: false,
        isIncompleteVoicingTemplate: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'sus2',
        intervals: [0, 2, 7],
        requiredIntervals: [0, 2, 7],
        signatureIntervals: [2],
        symbolSuffix: 'sus2',
        priority: 12,
        category: 'triad',
        qualityDependsOnThird: false,
        omissionLabelMode: 'none',
    },
    {
        type: 'sus4',
        intervals: [0, 5, 7],
        requiredIntervals: [0, 5, 7],
        signatureIntervals: [5],
        symbolSuffix: 'sus4',
        priority: 12,
        category: 'triad',
        qualityDependsOnThird: false,
        omissionLabelMode: 'none',
    },
    {
        type: 'dominant7',
        intervals: [0, 4, 7, 10],
        requiredIntervals: [0, 4, 7, 10],
        signatureIntervals: [10],
        symbolSuffix: '7',
        priority: 18,
        category: 'seventh',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'major7',
        intervals: [0, 4, 7, 11],
        requiredIntervals: [0, 4, 7, 11],
        signatureIntervals: [11],
        symbolSuffix: 'maj7',
        priority: 18,
        category: 'seventh',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'minor7',
        intervals: [0, 3, 7, 10],
        requiredIntervals: [0, 3, 7, 10],
        signatureIntervals: [10],
        symbolSuffix: 'm7',
        priority: 18,
        category: 'seventh',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'halfDiminished7',
        intervals: [0, 3, 6, 10],
        requiredIntervals: [0, 3, 6, 10],
        signatureIntervals: [6, 10],
        symbolSuffix: 'm7b5',
        priority: 21,
        category: 'seventh',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'diminished7',
        intervals: [0, 3, 6, 9],
        requiredIntervals: [0, 3, 6, 9],
        signatureIntervals: [6, 9],
        symbolSuffix: 'dim7',
        priority: 21,
        category: 'seventh',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: '6',
        intervals: [0, 4, 7, 9],
        requiredIntervals: [0, 4, 7],
        optionalIntervals: [9],
        signatureIntervals: [9],
        symbolSuffix: '6',
        priority: 16,
        category: 'triad',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'minor6',
        intervals: [0, 3, 7, 9],
        requiredIntervals: [0, 3, 7],
        optionalIntervals: [9],
        signatureIntervals: [9],
        symbolSuffix: 'm6',
        priority: 16,
        category: 'triad',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'add9',
        intervals: [0, 2, 4, 7],
        requiredIntervals: [0, 4, 7],
        optionalIntervals: [2],
        signatureIntervals: [2],
        symbolSuffix: 'add9',
        priority: 15,
        category: 'triad',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'minorAdd9',
        intervals: [0, 2, 3, 7],
        requiredIntervals: [0, 3, 7],
        optionalIntervals: [2],
        signatureIntervals: [2],
        symbolSuffix: 'madd9',
        priority: 15,
        category: 'triad',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'add11',
        intervals: [0, 4, 5, 7],
        requiredIntervals: [0, 4, 7],
        optionalIntervals: [5],
        signatureIntervals: [5],
        symbolSuffix: 'add11',
        priority: 15,
        category: 'triad',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'minorAdd11',
        intervals: [0, 3, 5, 7],
        requiredIntervals: [0, 3, 7],
        optionalIntervals: [5],
        signatureIntervals: [5],
        symbolSuffix: 'madd11',
        priority: 15,
        category: 'triad',
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: '6/9',
        intervals: [0, 2, 4, 7, 9],
        requiredIntervals: [0, 4, 7],
        optionalIntervals: [2, 9],
        signatureIntervals: [2, 9],
        symbolSuffix: '6/9',
        priority: 22,
        category: 'extended',
        qualityDependsOnThird: false,
        omissionLabelMode: 'none'
    },
    {
        type: '7sus4',
        intervals: [0, 5, 7, 10],
        requiredIntervals: [0, 5, 7, 10],
        signatureIntervals: [5, 10],
        symbolSuffix: '7sus4',
        priority: 19,
        category: 'seventh',
        qualityDependsOnThird: false,
        omissionLabelMode: 'none',
    },
    {
        type: '9',
        intervals: [0, 2, 4, 7, 10],
        requiredIntervals: [0, 4, 10],
        optionalIntervals: [2, 7],
        omittableIntervals: [7],
        signatureIntervals: [2],
        symbolSuffix: '9',
        priority: 24,
        category: 'extended',
        requiresSeventh: true,
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'major9',
        intervals: [0, 2, 4, 7, 11],
        requiredIntervals: [0, 4, 11],
        optionalIntervals: [2, 7],
        omittableIntervals: [7],
        signatureIntervals: [2],
        symbolSuffix: 'maj9',
        priority: 24,
        category: 'extended',
        requiresSeventh: true,
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'minor9',
        intervals: [0, 2, 3, 7, 10],
        requiredIntervals: [0, 3, 10],
        optionalIntervals: [2, 7],
        omittableIntervals: [7],
        signatureIntervals: [2],
        symbolSuffix: 'm9',
        priority: 24,
        category: 'extended',
        requiresSeventh: true,
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: '11',
        intervals: [0, 2, 4, 5, 7, 10],
        requiredIntervals: [0, 4, 10],
        optionalIntervals: [2, 5, 7],
        omittableIntervals: [7],
        signatureIntervals: [5],
        symbolSuffix: '11',
        priority: 27,
        category: 'extended',
        requiresSeventh: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'minor11',
        intervals: [0, 2, 3, 5, 7, 10],
        requiredIntervals: [0, 3, 10],
        optionalIntervals: [2, 5, 7],
        omittableIntervals: [7],
        signatureIntervals: [5],
        symbolSuffix: 'm11',
        priority: 27,
        category: 'extended',
        requiresSeventh: true,
        omissionLabelMode: 'none',
    },
    {
        type: '13',
        intervals: [0, 2, 4, 7, 9, 10],
        requiredIntervals: [0, 4, 10],
        optionalIntervals: [2, 7, 9],
        omittableIntervals: [7],
        signatureIntervals: [9],
        symbolSuffix: '13',
        priority: 30,
        category: 'extended',
        requiresSeventh: true,
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'major13',
        intervals: [0, 2, 4, 7, 9, 11],
        requiredIntervals: [0, 4, 11],
        optionalIntervals: [2, 7, 9],
        omittableIntervals: [7],
        signatureIntervals: [9],
        symbolSuffix: 'maj13',
        priority: 30,
        category: 'extended',
        requiresSeventh: true,
        qualityDependsOnThird: true,
        omissionLabelMode: 'none',
    },
    {
        type: 'dominant7No3',
        intervals: [0, 7, 10],
        requiredIntervals: [0, 7, 10],
        optionalIntervals: [],
        omittableIntervals: [],
        signatureIntervals: [10],
        symbolSuffix: '7',
        priority: 20,
        category: 'seventh',
        requiresSeventh: true,
        qualityDependsOnThird: false,
        isIncompleteVoicingTemplate: true,
        omissionLabelMode: 'no3',
    },
    {
        type: 'major7No3',
        intervals: [0, 7, 11],
        requiredIntervals: [0, 7, 11],
        optionalIntervals: [],
        omittableIntervals: [],
        signatureIntervals: [11],
        symbolSuffix: 'maj7',
        priority: 20,
        category: 'seventh',
        requiresSeventh: true,
        qualityDependsOnThird: false,
        isIncompleteVoicingTemplate: true,
        omissionLabelMode: 'no3',
    },
    {
        type: 'minor7No5',
        intervals: [0, 3, 10],
        requiredIntervals: [0, 3, 10],
        optionalIntervals: [],
        omittableIntervals: [],
        signatureIntervals: [10],
        symbolSuffix: 'm7',
        priority: 20,
        category: 'seventh',
        requiresSeventh: true,
        qualityDependsOnThird: true,
        isIncompleteVoicingTemplate: true,
        omissionLabelMode: 'no5',
    },
    {
        type: 'dominant7No5',
        intervals: [0, 4, 10],
        requiredIntervals: [0, 4, 10],
        optionalIntervals: [],
        omittableIntervals: [],
        signatureIntervals: [10],
        symbolSuffix: '7',
        priority: 20,
        category: 'seventh',
        requiresSeventh: true,
        qualityDependsOnThird: true,
        isIncompleteVoicingTemplate: true,
        omissionLabelMode: 'no5',
    },
    {
        type: 'major7No5',
        intervals: [0, 4, 11],
        requiredIntervals: [0, 4, 11],
        optionalIntervals: [],
        omittableIntervals: [],
        signatureIntervals: [11],
        symbolSuffix: 'maj7',
        priority: 20,
        category: 'seventh',
        requiresSeventh: true,
        qualityDependsOnThird: true,
        isIncompleteVoicingTemplate: true,
        omissionLabelMode: 'no5',
    },
]
