import type {ChordTemplate} from './interfaces'

export const PITCH_CLASS_NAMES_SHARP = [
    'C',
    'C#',
    'D',
    'D#',
    'E',
    'F',
    'F#',
    'G',
    'G#',
    'A',
    'A#',
    'B',
]

export const CHORD_TEMPLATES: ChordTemplate[] = [
    {
        type: 'major',
        intervals: [0, 4, 7],
        requiredIntervals: [0, 4, 7],
        symbolSuffix: '',
        priority: 10,
        category: 'triad',
    },
    {
        type: 'minor',
        intervals: [0, 3, 7],
        requiredIntervals: [0, 3, 7],
        symbolSuffix: 'm',
        priority: 10,
        category: 'triad',
    },
    {
        type: 'sus2',
        intervals: [0, 2, 7],
        requiredIntervals: [0, 2, 7],
        symbolSuffix: 'sus2',
        priority: 12,
        category: 'triad',
    },
    {
        type: 'sus4',
        intervals: [0, 5, 7],
        requiredIntervals: [0, 5, 7],
        symbolSuffix: 'sus4',
        priority: 12,
        category: 'triad',
    },
    {
        type: 'dominant7',
        intervals: [0, 4, 7, 10],
        requiredIntervals: [0, 4, 7, 10],
        symbolSuffix: '7',
        priority: 18,
        category: 'seventh',
    },
    {
        type: 'major7',
        intervals: [0, 4, 7, 11],
        requiredIntervals: [0, 4, 7, 11],
        symbolSuffix: 'maj7',
        priority: 18,
        category: 'seventh',
    },
    {
        type: 'minor7',
        intervals: [0, 3, 7, 10],
        requiredIntervals: [0, 3, 7, 10],
        symbolSuffix: 'm7',
        priority: 18,
        category: 'seventh',
    },
    {
        type: '6',
        intervals: [0, 4, 7, 9],
        requiredIntervals: [0, 4, 7],
        optionalIntervals: [9],
        symbolSuffix: '6',
        priority: 16,
        category: 'triad',
    },
    {
        type: 'minor6',
        intervals: [0, 3, 7, 9],
        requiredIntervals: [0, 3, 7],
        optionalIntervals: [9],
        symbolSuffix: 'm6',
        priority: 16,
        category: 'triad',
    },
    {
        type: 'add9',
        intervals: [0, 2, 4, 7],
        requiredIntervals: [0, 4, 7],
        optionalIntervals: [2],
        symbolSuffix: 'add9',
        priority: 15,
        category: 'triad',
    },
    {
        type: 'minorAdd9',
        intervals: [0, 2, 3, 7],
        requiredIntervals: [0, 3, 7],
        optionalIntervals: [2],
        symbolSuffix: 'madd9',
        priority: 15,
        category: 'triad',
    },
    {
        type: 'add11',
        intervals: [0, 4, 5, 7],
        requiredIntervals: [0, 4, 7],
        optionalIntervals: [5],
        symbolSuffix: 'add11',
        priority: 15,
        category: 'triad',
    },
    {
        type: 'minorAdd11',
        intervals: [0, 3, 5, 7],
        requiredIntervals: [0, 3, 7],
        optionalIntervals: [5],
        symbolSuffix: 'madd11',
        priority: 15,
        category: 'triad',
    },
    {
        type: '6/9',
        intervals: [0, 2, 4, 7, 9],
        requiredIntervals: [0, 4, 7],
        optionalIntervals: [2, 9],
        symbolSuffix: '6/9',
        priority: 22,
        category: 'extended',
    },
    {
        type: '9',
        intervals: [0, 2, 4, 7, 10],
        requiredIntervals: [0, 4, 10],
        optionalIntervals: [2, 7],
        omittableIntervals: [7],
        symbolSuffix: '9',
        priority: 24,
        category: 'extended',
        requiresSeventh: true,
    },
    {
        type: 'major9',
        intervals: [0, 2, 4, 7, 11],
        requiredIntervals: [0, 4, 11],
        optionalIntervals: [2, 7],
        omittableIntervals: [7],
        symbolSuffix: 'maj9',
        priority: 24,
        category: 'extended',
        requiresSeventh: true,
    },
    {
        type: 'minor9',
        intervals: [0, 2, 3, 7, 10],
        requiredIntervals: [0, 3, 10],
        optionalIntervals: [2, 7],
        omittableIntervals: [7],
        symbolSuffix: 'm9',
        priority: 24,
        category: 'extended',
        requiresSeventh: true,
    },
    {
        type: '11',
        intervals: [0, 2, 4, 5, 7, 10],
        requiredIntervals: [0, 4, 10],
        optionalIntervals: [2, 5, 7],
        omittableIntervals: [7],
        symbolSuffix: '11',
        priority: 27,
        category: 'extended',
        requiresSeventh: true,
    },
    {
        type: 'minor11',
        intervals: [0, 2, 3, 5, 7, 10],
        requiredIntervals: [0, 3, 10],
        optionalIntervals: [2, 5, 7],
        omittableIntervals: [7],
        symbolSuffix: 'm11',
        priority: 27,
        category: 'extended',
        requiresSeventh: true,
    },
    {
        type: '13',
        intervals: [0, 2, 4, 7, 9, 10],
        requiredIntervals: [0, 4, 10],
        optionalIntervals: [2, 7, 9],
        omittableIntervals: [7],
        symbolSuffix: '13',
        priority: 30,
        category: 'extended',
        requiresSeventh: true,
    },
    {
        type: 'major13',
        intervals: [0, 2, 4, 7, 9, 11],
        requiredIntervals: [0, 4, 11],
        optionalIntervals: [2, 7, 9],
        omittableIntervals: [7],
        symbolSuffix: 'maj13',
        priority: 30,
        category: 'extended',
        requiresSeventh: true,
    },
]
